######## Stellar info ########
stellar:
  version: '1.29.1'
  homepage: 'https://xaoxuu.com/wiki/stellar/'
  repo: 'https://github.com/xaoxuu/hexo-theme-stellar'
  main_css: /css/main.css
  main_js: /js/main.js


######## head tags ########
preconnect:
  # - https://gcore.jsdelivr.net
  # - https://cdn.jsdelivr.net
  # - https://unpkg.com

open_graph:
  enable: true
  twitter_id: # for open_graph meta


######## Sidebar ########
# å·¦ä¸Šè§’æ˜¾ç¤ºçš„ logo åŒºåŸŸï¼ŒåŒ…å«å›¾æ ‡ã€å¤§æ ‡é¢˜ã€å‰¯æ ‡é¢˜
logo:
  avatar: '[{config.avatar}](/about/)' # you can set avatar link in _config.yml or '[https://xxx.png](/about/)'
  title: '[{config.title}](/)' # you can set html tag like: '[<img no-lazy height="32px" src="xxx"/>](/)'
  subtitle: '{config.subtitle}' # 'æ–‡å­—1 | æ–‡å­—2' (é¼ æ ‡æ”¾ä¸Šå»ä¼šåˆ‡æ¢åˆ°æ–‡å­—2)

# ä¾§è¾¹æ ä¸»åŠŸèƒ½å¯¼èˆªèœå•
menubar:
  columns: 4 # ä¸€è¡Œå¤šå°‘ä¸ª
  items: # å¯æŒ‰ç…§è‡ªå·±éœ€æ±‚å¢åŠ ï¼Œç¬¦åˆä»¥ä¸‹æ ¼å¼å³å¯
      - id: post
        title: é˜¿é»„è¯´
        url: /
      - id: wiki
        title: é˜¿é»„
        url: /tags/
      - id: explore
        title: æ¢ç´¢
        url: /about/
      - id: social
        title: é˜¿é»„å‹
        url: /link/


######## Main ########
# ç«™ç‚¹ä¸»ç»“æ„æ ‘
site_tree:
  # -- åˆ—è¡¨ç±»é¡µé¢ -- #
  # ä¸»é¡µé…ç½®
  home:
    leftbar: welcome, recent
    rightbar: 
  # åšå®¢åˆ—è¡¨é¡µé…ç½®
  index_blog:
    base_dir: blog # åªå½±å“è‡ªåŠ¨ç”Ÿæˆçš„é¡µé¢è·¯å¾„
    menu_id: post # æœªåœ¨ front-matter ä¸­æŒ‡å®š menu_id æ—¶ï¼Œlayout ä¸º post çš„é¡µé¢é»˜è®¤ä½¿ç”¨è¿™é‡Œé…ç½®çš„ menu_id
    leftbar: welcome, recent # for categories/tags/archives
    rightbar: 
    nav_tabs:  # è¿‘æœŸå‘å¸ƒ åˆ†ç±» æ ‡ç­¾ ä¸“æ  å½’æ¡£ and ...
      # 'æœ‹å‹æ–‡ç« ': /friends/rss/
  # åšå®¢ä¸“æ åˆ—è¡¨é¡µé…ç½®
  index_topic:
    base_dir: topic # åªå½±å“è‡ªåŠ¨ç”Ÿæˆçš„é¡µé¢è·¯å¾„
    menu_id: post # æœªåœ¨ front-matter ä¸­æŒ‡å®š menu_id æ—¶ï¼Œlayout ä¸º topic çš„é¡µé¢é»˜è®¤ä½¿ç”¨è¿™é‡Œé…ç½®çš„ menu_id
  # æ–‡æ¡£åˆ—è¡¨é¡µé…ç½®
  index_wiki:
    base_dir: wiki # åªå½±å“è‡ªåŠ¨ç”Ÿæˆçš„é¡µé¢è·¯å¾„
    menu_id: wiki # æœªåœ¨ front-matter ä¸­æŒ‡å®š menu_id æ—¶ï¼Œlayout ä¸º wiki çš„é¡µé¢é»˜è®¤ä½¿ç”¨è¿™é‡Œé…ç½®çš„ menu_id
    leftbar: related, recent # for wiki
    rightbar: 
    nav_tabs:
      # 'more': https://github.com/xaoxuu
  # -- å†…å®¹ç±»é¡µé¢ -- #
  # åšå®¢æ–‡ç« å†…é¡µé…ç½®
  post:
    menu_id: post # æœªåœ¨ front-matter ä¸­æŒ‡å®š menu_id æ—¶ï¼Œlayout ä¸º post çš„é¡µé¢é»˜è®¤ä½¿ç”¨è¿™é‡Œé…ç½®çš„ menu_id
    leftbar: related, recent # for pages using 'layout:post'
    rightbar: ghrepo, toc
  # åšå®¢ä¸“æ æ–‡ç« å†…é¡µé…ç½®
  topic:
    menu_id: post
  # æ–‡æ¡£å†…é¡µé…ç½®
  wiki:
    menu_id: wiki # æœªåœ¨ front-matter ä¸­æŒ‡å®š menu_id æ—¶ï¼Œlayout ä¸º wiki çš„é¡µé¢é»˜è®¤ä½¿ç”¨è¿™é‡Œé…ç½®çš„ menu_id
    leftbar: tree, related, recent # for wiki
    rightbar: ghrepo, toc
  # ç¬”è®°æœ¬åˆ—è¡¨é¡µé…ç½®
  notebooks:
    base_dir: notebooks # ç¬”è®°æœ¬åˆ—è¡¨é¡µçš„è·¯å¾„ã€‚ä»¥åŠæœªæŒ‡å®š base_dir çš„ç¬”è®°æœ¬çš„è·¯å¾„å‰ç¼€ã€‚
    menu_id: notebooks # ç¬”è®°æœ¬åˆ—è¡¨é¡µé«˜äº®çš„ä¸»å¯¼èˆªæ èœå•æŒ‰é’®ã€‚
    # ç¬”è®°æœ¬åˆ—è¡¨é¡µçš„å·¦ä¾§æ å’Œå³ä¾§æ ã€‚
    leftbar: recent # recent within all notebooks
    rightbar: null
  # ç¬”è®°åˆ—è¡¨é¡µé…ç½®
  notes:
    # ç¬”è®°åˆ—è¡¨é¡µå’Œç¬”è®°é¡µé«˜äº®çš„ä¸»å¯¼èˆªæ èœå•æŒ‰é’®ã€‚
    # å¯ä»¥åœ¨ç¬”è®°æœ¬ yaml çš„ menu_id å­—æ®µä¸­è¦†ç›–æ­¤å‚æ•°ã€‚
    # å¯ä»¥åœ¨ç¬”è®°çš„ front-matter/menu_id ä¸­è¦†ç›–æ­¤å‚æ•°ã€‚
    menu_id: notebooks
    # ç¬”è®°åˆ—è¡¨é¡µçš„å·¦ä¾§æ å’Œå³ä¾§æ ã€‚å¯ä»¥åœ¨ç¬”è®°æœ¬ yaml çš„ leftbar å’Œ rightbar å­—æ®µä¸­è¦†ç›–æ­¤å‚æ•°ã€‚
    leftbar: tagtree, recent # recent of current notebook
    rightbar: null
  # ç¬”è®°é¡µé…ç½®
  note:
    # ç¬”è®°é¡µçš„å·¦ä¾§æ å’Œå³ä¾§æ 
    # å¯ä»¥åœ¨ç¬”è®°æœ¬ yaml çš„ note_leftbar å’Œ note_rightbar å­—æ®µä¸­è¦†ç›–æ­¤å‚æ•°ã€‚
    # å¯ä»¥åœ¨ç¬”è®°çš„ front-matter/leftbar å’Œ rightbar å­—æ®µä¸­è¦†ç›–æ­¤å‚æ•°ã€‚
    leftbar: tagtree, recent # recent of current notebook
    rightbar: toc
  # ä½œè€…ä¿¡æ¯é…ç½®
  author: 
    base_dir: author # åªå½±å“è‡ªåŠ¨ç”Ÿæˆçš„é¡µé¢è·¯å¾„
    menu_id: post
    leftbar: recent, timeline
    rightbar: timeline
  # é”™è¯¯é¡µé…ç½®
  error_page:
    menu_id: post
    '404': '/404.html'
    leftbar: recent, timeline
    rightbar: timeline
  # å…¶å®ƒè‡ªå®šä¹‰é¡µé¢é…ç½® layout: page
  page:
    leftbar: recent
    rightbar: toc


######## Notebook ########
notebook:
  # å¦‚æœæ²¡æœ‰æŒ‡å®š excerpt å’Œ descriptionï¼Œå°†è‡ªåŠ¨å–å¤šé•¿çš„å†…å®¹ä½œä¸ºæ–‡ç« æ‘˜è¦ã€‚
  auto_excerpt: 128
  # å¯ä»¥ä¸ºæŸä¸ª tag è®¾å®šå›¾æ ‡ï¼ˆæ˜¾ç¤ºåœ¨æ ‡ç­¾æ ‘ä¸­ï¼‰ã€‚
  tagcons:
    '': solar:hashtag-linear
  # æ¯é¡µæ˜¾ç¤ºå¤šå°‘ç¯‡ç¬”è®°ã€‚0 è¡¨ç¤ºä¸åˆ†é¡µï¼Œnull åˆ™ fallback åˆ° hexo çš„é…ç½®ã€‚
  # å¯ä»¥åœ¨ç¬”è®°æœ¬ yaml çš„ per_page å­—æ®µä¸­è¦†ç›–æ­¤å‚æ•°ã€‚
  per_page: null
  # ç¬”è®°çš„æ’åºæ–¹å¼ã€‚é»˜è®¤æŒ‰ç…§ updated é™åºæ’åºã€‚
  # å¯ä»¥åœ¨ç¬”è®°æœ¬ yaml çš„ order_by å­—æ®µä¸­è¦†ç›–æ­¤å‚æ•°ã€‚
  # æ³¨æ„ï¼šç½®é¡¶çš„ç¬”è®°ä¼šå§‹ç»ˆæ’åœ¨æœ€å‰é¢ã€‚
  # åœ¨ front-matter ä¸­è®¾ç½® pin:true|number æˆ– sticky:true|number æ¥ç½®é¡¶ã€‚
  order_by: -updated
  # æ˜¯å¦åœ¨ç¬”è®°é¡µé¢æ˜¾ç¤ºè®¸å¯åè®®ã€‚false è¡¨ç¤ºä¸æ˜¾ç¤ºã€‚true è¡¨ç¤ºæ²¿ç”¨ä¸»é¢˜è®¸å¯åè®®å†…å®¹ã€‚ä¹Ÿå¯ä»¥ç»™å®šå…·ä½“çš„æ–‡æœ¬æŒ‡å®šåè®®å†…å®¹ã€‚
  # å¯ä»¥åœ¨ç¬”è®°æœ¬ yaml çš„ license å­—æ®µä¸­è¦†ç›–æ­¤å‚æ•°ã€‚
  # å¯ä»¥åœ¨ç¬”è®°çš„ front-matter/license ä¸­è¦†ç›–æ­¤å‚æ•°ã€‚
  license: false
  # æ˜¯å¦åœ¨ç¬”è®°é¡µé¢æ˜¾ç¤ºåˆ†äº«æŒ‰é’®ã€‚
  # å¯ä»¥åœ¨ç¬”è®°æœ¬ yaml çš„ share å­—æ®µä¸­è¦†ç›–æ­¤å‚æ•°ã€‚
  # å¯ä»¥åœ¨ç¬”è®°çš„ front-matter/share ä¸­è¦†ç›–æ­¤å‚æ•°ã€‚
  share: false


######## Article ########
article:
  # æ–‡ç« ç±»å‹ï¼Œå†³å®šå¸ƒå±€é£æ ¼ï¼Œå¯ä»¥åœ¨ front-matter/topic/wiki ä¸­è¦†ç›–æ­¤å‚æ•°
  type: tech # tech: é»˜è®¤æŠ€æœ¯ç±»æ–‡ç« , story: å›¾æ–‡ç±»æ–‡ç« ï¼Œæ–‡å­—å’Œæ®µè½é—´å¢è·å¤§
  # ç¼©è¿›ä¸¤ä¸ªæ–‡å­—å®½åº¦ï¼Œé€‚åˆæ–‡å­—ç±»åšå®¢ï¼Œå¯ä»¥åœ¨ front-matter/topic/wiki ä¸­è¦†ç›–æ­¤å‚æ•°
  indent: # true / false
  # å¦‚æœæ²¡æœ‰æŒ‡å®šå°é¢ï¼Œæ˜¯å¦æ ¹æ® tags ä½œä¸ºå…³é”®è¯æœç´¢å°é¢å›¾ç‰‡ï¼Ÿ
  auto_cover: false # search from https://source.unsplash.com/
  # å°é¢å›¾å®½é«˜æ¯”
  cover_ratio: 2.4
  # å¦‚æœæ²¡æœ‰æŒ‡å®šæ¨ªå¹…ï¼Œæ˜¯å¦æ ¹æ® tags ä½œä¸ºå…³é”®è¯æœç´¢æ¨ªå¹…å›¾ç‰‡ï¼Ÿ
  auto_banner: false # search from https://source.unsplash.com/
  # å¦‚æœæ²¡æœ‰æŒ‡å®š excerpt å’Œ descriptionï¼Œå°†è‡ªåŠ¨å–å¤šé•¿çš„å†…å®¹ä½œä¸ºæ–‡ç« æ‘˜è¦ï¼Ÿ
  auto_excerpt: 128
  # åˆ†ç±»é¢œè‰²
  category_color:
    'æ¢ç´¢å·': '#f44336'
  # æ–‡ç« è®¸å¯åè®®
  license: 'æœ¬æ–‡é‡‡ç”¨ [ç½²å-éå•†ä¸šæ€§ä½¿ç”¨-ç›¸åŒæ–¹å¼å…±äº« 4.0 å›½é™…](https://creativecommons.org/licenses/by-nc-sa/4.0/) è®¸å¯åè®®ï¼Œè½¬è½½è¯·æ³¨æ˜å‡ºå¤„ã€‚'
  # åˆ†äº«
  share: # [wechat, weibo, email, link]
  # ç›¸å…³æ–‡ç« ï¼Œéœ€è¦å®‰è£…æ’ä»¶ (for layout: post)
  # npm i hexo-related-popular-posts
  related_posts:
    enable: false
    max_count: 5

search:
  service: local_search # local_search, algolia_search, todo...
  local_search: # åœ¨ front-matter ä¸­è®¾ç½® indexing:false æ¥é¿å…è¢«æœç´¢ç´¢å¼•
    field: all # post, page, all
    path: /search.json # æœç´¢æ–‡ä»¶å­˜æ”¾ä½ç½®
    content: true # æ˜¯å¦æœç´¢å†…å®¹
    skip_search:  # æŒ‡å®š path ä¸­çš„å†…å®¹ä¸è¢«æœç´¢ã€‚
  algolia_search: # Docsearch https://docsearch.algolia.com/apply/ ç”³è¯·
    appId: 
    apiKey: 
    indexName: 
    js: https://gcore.jsdelivr.net/algoliasearch/3/algoliasearch.min.js


######## Comments ########
######## Comments ########
comments:
  service: waline # beaudar, utterances, giscus, twikoo, waline, artalk
  comment_title: å¿«æ¥å‚ä¸è®¨è®ºå§~

  # Waline
  # https://waline.js.org/
  waline:
    js: https://gcore.jsdelivr.net/npm/@waline/client@3.1.3/dist/waline.js
    css: https://gcore.jsdelivr.net/npm/@waline/client@3.1.3/dist/waline.css
    meta_css: https://gcore.jsdelivr.net/npm/@waline/client@3.1.3/dist/waline-meta.css
    # Waline server address url, you should set this to your own link
    serverURL: https://talk.laogoupro.us.kg/
    locale:
      placeholder:
        ğŸ˜å—¨ï¼Œæœ‹å‹ï¼Œç•™ä¸‹è„šå°å†èµ°å‘—ã€‚
    reaction: true




######## Footer ########
footer:
  social:
      github:
        icon: '<img src="https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.12/social/08a41b181ce68.svg"/>'
        url: /
      music:
        icon: '<img src="https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.12/social/3845874.svg"/>'
        url: /news/
      unsplash:
        icon: '<img src="https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.12/social/3616429.svg"/>'
        url: /air-/
      comments:
        icon: '<img src="https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.12/social/942ebbf1a4b91.svg"/>'
        url: /about123/#comments
      theme:
        icon: default:theme
        onclick: 'switchTheme()'
  sitemap:
      'åšå®¢':
        - '[è¿‘æœŸ](/)'
        - '[åˆ†ç±»](/tags/)'
        - '[æ ‡ç­¾](/air-/)'
      'ç¤¾äº¤':
        - '[å‹é“¾](/friends/)'
      'æ›´å¤š':
        - '[å…³äºæœ¬ç«™](/about/)'
        - '[GitHub](https://github.com/)'
  content: | # æ”¯æŒ Markdown æ ¼å¼
    æœ¬ç«™ç”± [{author.name}](/) ä½¿ç”¨ [{theme.name} {theme.version}]({theme.tree}) ä¸»é¢˜åˆ›å»ºã€‚
    æœ¬åšå®¢æ‰€æœ‰æ–‡ç« é™¤ç‰¹åˆ«å£°æ˜å¤–ï¼Œå‡é‡‡ç”¨ [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) è®¸å¯åè®®ï¼Œè½¬è½½è¯·æ³¨æ˜å‡ºå¤„ã€‚
    ä¸»é¢˜ç”¨æˆ·è¶Šå¤šï¼Œå¼€å‘è€…ç»´æŠ¤å’Œæ›´æ–°çš„ç§¯ææ€§å°±è¶Šé«˜ï¼Œå¦‚æœæ‚¨å–œæ¬¢æœ¬ä¸»é¢˜ï¼Œè¯·åœ¨é€‚å½“çš„ä½ç½®æ˜¾ç¤ºä¸»é¢˜ä¿¡æ¯å’Œä»“åº“é“¾æ¥ä»¥è¡¨æ”¯æŒã€‚


######## Tag Plugins ########
tag_plugins:
  # {% box %} / {% note %}
  note:
    default_color: '' # light, dark, red, orange, yellow, green, cyan, blue, purple, warning, error
    border: true # true / false
  # {% checkbox %}
  checkbox:
    interactive: false # enable interactive for user
  # {% quot %}
  quot:
    default: # å¯ä»¥è‡ªè¡Œé…ç½®å¤šç§å›¾æ ‡æ–¹æ¡ˆ
      prefix: https://bu.dusays.com/2022/10/24/63567d3e092ff.png
      suffix: https://bu.dusays.com/2022/10/24/63567d3e0ab55.png
    hashtag:
      prefix: https://bu.dusays.com/2022/10/24/63567d3e07da3.png
    question:
      prefix: ph:seal-question-fill
  # {% emoji %}
  emoji:
    default: https://gcore.jsdelivr.net/gh/cdn-x/emoji/qq/{name}.gif
    twemoji: https://gcore.jsdelivr.net/gh/twitter/twemoji/assets/svg/{name}.svg
    qq: https://gcore.jsdelivr.net/gh/cdn-x/emoji/qq/{name}.gif
    aru: https://gcore.jsdelivr.net/gh/cdn-x/emoji/aru-l/{name}.gif
    tieba: https://gcore.jsdelivr.net/gh/cdn-x/emoji/tieba/{name}.png
    blobcat: https://gcore.jsdelivr.net/gh/norevi/waline-blobcatemojis@1.0/blobs/{name}.png
  icon:
    # ç•™ç©ºæ—¶ï¼Œå›¾æ ‡å’Œæ–‡å­—é¢œè‰²ç›¸åŒ
    default_color: accent # theme, accent, red, orange, yellow, green, cyan, blue, purple
  # {% button æ ‡é¢˜ é“¾æ¥ %}
  button:
    default_color: theme # theme, accent, red, orange, yellow, green, cyan, blue, purple
  # {% image %}
  image:
    fancybox: false # true, false
  # {% copy xxx %}
  copy:
    toast: å¤åˆ¶æˆåŠŸ
  # {% timeline %}
  timeline:
    max-height: 80vh
  # {% mark %}
  mark:
    default_color: yellow # light, dark, red, orange, yellow, green, cyan, blue, purple, warning, error
  # {% hashtag %}
  hashtag:
    default_color: # red, orange, yellow, green, cyan, blue, purple
  # {% okr o1 percent:0.5 status:normal %}
  okr:
    border: true # æ˜¯å¦æ˜¾ç¤ºè¾¹æ¡†
    status: # å¯ä»¥è‡ªè¡Œå¢åŠ 
      # è¿›è¡Œä¸­çŠ¶æ€
      in_track:
        color: blue # red, orange, yellow, green, cyan, blue, purple
        label: æ­£å¸¸
      at_risk: 
        color: yellow
        label: é£é™©
      off_track:
        color: orange
        label: å»¶æœŸ
      # ç»“æœçŠ¶æ€
      finished:
        color: green
        label: å·²å®Œæˆ
      unfinished:
        color: red
        label: æœªå®Œæˆ
  # {% gallery %}
  gallery:
    layout: grid # grid / flow
    size: mix # s / m / l / xl / mix
    ratio: square # origin / square


# åŸºç¡€ä¾èµ–
dependencies:
  jquery: https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js
  marked: https://cdn.jsdelivr.net/npm/marked@13.0.1/lib/marked.umd.min.js


# å†…ç½®æœåŠ¡ï¼ŒæŒ‰éœ€åŠ è½½ï¼ˆé¡µé¢å†…ç”¨åˆ°äº†å°±ä¼šåŠ è½½ï¼Œæ²¡æœ‰ç”¨åˆ°å°±ä¸ä¼šåŠ è½½ï¼‰
data_services:
  # å¤–éƒ¨ md æ¸²æŸ“
  mdrender:
    js: /js/services/mdrender.js
  # æ•°æ®å¡«å……ç±»
  siteinfo:
    js: /js/services/siteinfo.js
    # è®¾ç½® api å¯ä»¥è‡ªåŠ¨æå–ç½‘é¡µæ ‡é¢˜ã€å›¾æ ‡ï¼ŒæœåŠ¡éƒ¨ç½²æ–¹æ³•ï¼šhttps://github.com/xaoxuu/site-info-api/
    # æ¥å£æµ‹è¯•é€šè¿‡åï¼ŒæŠŠæŒ‰é’®çš„ href éƒ¨åˆ†æ›¿æ¢æˆ {href} ä¹‹åå¡«å†™åˆ°ä¸‹æ–¹ï¼Œä¾‹å¦‚ï¼šhttps://api.vlts.cc/site_info/v1?url={href}
    api: